# Generated by Django 4.2.7 on 2025-10-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorosession',
            name='session_name',
            field=models.CharField(default='جلسه مطالعه', max_length=200),
        ),
    ]
