services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "resume_db", "-U", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - postgres_data_resume:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - 8000:8000
      - 8001:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/django_db
      - DEBUG=True
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 config.wsgi:application"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - media_files:/app/media
      - static_files:/app/staticfiles

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
      - 3001:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  postgres_data_resume:
  media_files:
  static_files:
