# Generated by Django 5.2.6 on 2025-09-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_certification_education_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='expiry_date',
        ),
    ]
