# Generated by Django 5.2.6 on 2025-09-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_remove_certification_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='github_link',
        ),
        migrations.AddField(
            model_name='project',
            name='production_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
