# Generated by Django 4.2.7 on 2025-10-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0007_setting"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Setting",
        ),
    ]
